from dt.plot.plots import show_gradient_boost_classifier_lib_impl, show_random_forest_classifier_lib_impl, \
    show_decision_tree_classifier_lib_impl, show_my_decision_tree_impl, show_my_random_forest_impl

show_decision_tree_classifier_lib_impl()
show_random_forest_classifier_lib_impl()
show_gradient_boost_classifier_lib_impl()
show_my_decision_tree_impl()
show_my_random_forest_impl()
